spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/Banhang?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
    username: root
    password: Huumod7911#
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081

jwt:
  signerKey: "8d39391ea33e595d446e01707001ece7f56e0ae2b1798209a54592c1cc6159cd"